# Generated by Django 4.2.18 on 2025-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissingPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("last_seen_location", models.CharField(max_length=255)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
