# Generated by Django 4.2.18 on 2025-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_missingperson_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingperson",
            name="username",
            field=models.CharField(default=1, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
