# Generated by Django 4.2.18 on 2025-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_missingperson_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="missingperson", name="created_by",),
        migrations.RemoveField(model_name="missingperson", name="username",),
    ]
