name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 400 private_key.pem

    - name: Debug GitHub Runner Environment
      run: |
        echo "Current User:"
        whoami
        echo "Home Directory: $HOME"
        echo "Checking if .ssh exists:"
        ls -ld $HOME/.ssh || echo ".ssh does not exist"
        echo "Checking permissions of $HOME:"
        ls -ld $HOME
        echo "Checking available disk space:"
        df -h



    - name: Add EC2 Host to Known Hosts
      run: |
        export SSH_DIR="$HOME/.ssh"
        sudo mkdir -p $SSH_DIR  # Use sudo to ensure it works
        sudo chmod 700 $SSH_DIR  # Ensure correct permissions
        ssh-keyscan -H ec2-44-202-12-249.compute-1.amazonaws.com | sudo tee -a $SSH_DIR/known_hosts > /dev/null
        sudo chmod 644 $SSH_DIR/known_hosts
        echo "Using $SSH_DIR as SSH directory."



    - name: Copy Files to EC2
      run: |
        scp -o UserKnownHostsFile=/tmp/.ssh/known_hosts -i private_key.pem -r . ubuntu@ec2-44-202-12-249.compute-1.amazonaws.com:/home/ubuntu/django_project/Missing_MeetUp_Django


    - name: Deploy on EC2
      run: |
        echo "Starting SSH to EC2..."
        ssh -i private_key.pem ubuntu@ec2-44-202-12-249.compute-1.amazonaws.com << 'EOF'
        echo "Updating & Installing Dependencies..."
        sudo apt update -y && sudo apt install -y docker.io

        echo "Navigating to project directory..."
        cd /home/ubuntu/django_project/Missing_MeetUp_Django

        echo "Stopping and Removing Old Containers..."
        docker ps -aq --filter name=missing-meetup-django-container | xargs -r docker rm -f

        echo "Building and Running the New Docker Container..."
        docker build -t missing-meetup-django .
        docker run -d --name missing-meetup-django-container -p 8080:8080 missing-meetup-django
        EOF

    - name: Clean Up
      run: rm -f private_key.pem
