name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 400 private_key.pem

    - name: Debug SSH Directory
      run: |
        echo "Home Directory: $HOME"
        ls -ld $HOME
        ls -ld ~/.ssh || echo "No .ssh directory found"


    - name: Add EC2 Host to Known Hosts
      run: |
        mkdir -p $HOME/.ssh
        ssh-keyscan -H ec2-44-202-12-249.compute-1.amazonaws.com >> $HOME/.ssh/known_hosts

    - name: Copy Project Files to EC2
      run: |
        scp -i private_key.pem -r . ubuntu@ec2-44-202-12-249.compute-1.amazonaws.com:/home/ubuntu/missing-meetup

    - name: Deploy on EC2
      run: |
        echo "Starting SSH to EC2..."
        ssh -i private_key.pem ubuntu@ec2-44-202-12-249.compute-1.amazonaws.com << 'EOF'
        echo "Updating & Installing Dependencies..."
        sudo apt update -y && sudo apt install -y docker.io

        echo "Navigating to project directory..."
        cd /home/ubuntu/missing-meetup

        echo "Stopping and Removing Old Containers..."
        docker ps -aq --filter name=missing-meetup-django-container | xargs -r docker rm -f

        echo "Building and Running the New Docker Container..."
        docker build -t missing-meetup-django .
        docker run -d --name missing-meetup-django-container -p 8080:8080 missing-meetup-django
        EOF

    - name: Clean Up
      run: rm -f private_key.pem
